// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/dart_pty.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class DartPtyBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  DartPtyBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  DartPtyBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// \mainpage Dynamically Linked Dart API
  ///
  /// This exposes a subset of symbols from dart_api.h and dart_native_api.h
  /// available in every Dart embedder through dynamic linking.
  ///
  /// All symbols are postfixed with _DL to indicate that they are dynamically
  /// linked and to prevent conflicts with the original symbol.
  ///
  /// Link `dart_api_dl.c` file into your library and invoke
  /// `Dart_InitializeApiDL` with `NativeApi.initializeApiDLData`.
  ///
  /// Returns 0 on success.
  int Dart_InitializeApiDL(ffi.Pointer<ffi.Void> data) {
    return _Dart_InitializeApiDL(data);
  }

  late final _Dart_InitializeApiDLPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>(
        'Dart_InitializeApiDL',
      );
  late final _Dart_InitializeApiDL =
      _Dart_InitializeApiDLPtr.asFunction<
        int Function(ffi.Pointer<ffi.Void>)
      >();

  late final ffi.Pointer<
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Bool Function(ffi.Int64, ffi.Pointer<_Dart_CObject>)
      >
    >
  >
  _Dart_PostCObject_DL =
      _lookup<
        ffi.Pointer<
          ffi.NativeFunction<
            ffi.Bool Function(ffi.Int64, ffi.Pointer<_Dart_CObject>)
          >
        >
      >('Dart_PostCObject_DL');

  ffi.Pointer<
    ffi.NativeFunction<ffi.Bool Function(ffi.Int64, ffi.Pointer<_Dart_CObject>)>
  >
  get Dart_PostCObject_DL => _Dart_PostCObject_DL.value;

  set Dart_PostCObject_DL(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Bool Function(ffi.Int64, ffi.Pointer<_Dart_CObject>)
      >
    >
    value,
  ) => _Dart_PostCObject_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Int64, ffi.Int64)>>
  >
  _Dart_PostInteger_DL =
      _lookup<
        ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Int64, ffi.Int64)>>
      >('Dart_PostInteger_DL');

  ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Int64, ffi.Int64)>>
  get Dart_PostInteger_DL => _Dart_PostInteger_DL.value;

  set Dart_PostInteger_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Int64, ffi.Int64)>>
    value,
  ) => _Dart_PostInteger_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int64 Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Int64, ffi.Pointer<_Dart_CObject>)
            >
          >,
          ffi.Bool,
        )
      >
    >
  >
  _Dart_NewNativePort_DL =
      _lookup<
        ffi.Pointer<
          ffi.NativeFunction<
            ffi.Int64 Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<
                ffi.NativeFunction<
                  ffi.Void Function(ffi.Int64, ffi.Pointer<_Dart_CObject>)
                >
              >,
              ffi.Bool,
            )
          >
        >
      >('Dart_NewNativePort_DL');

  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int64 Function(
        ffi.Pointer<ffi.Char>,
        ffi.Pointer<
          ffi.NativeFunction<
            ffi.Void Function(ffi.Int64, ffi.Pointer<_Dart_CObject>)
          >
        >,
        ffi.Bool,
      )
    >
  >
  get Dart_NewNativePort_DL => _Dart_NewNativePort_DL.value;

  set Dart_NewNativePort_DL(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int64 Function(
          ffi.Pointer<ffi.Char>,
          ffi.Pointer<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Int64, ffi.Pointer<_Dart_CObject>)
            >
          >,
          ffi.Bool,
        )
      >
    >
    value,
  ) => _Dart_NewNativePort_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Int64)>>
  >
  _Dart_CloseNativePort_DL =
      _lookup<ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Int64)>>>(
        'Dart_CloseNativePort_DL',
      );

  ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Int64)>>
  get Dart_CloseNativePort_DL => _Dart_CloseNativePort_DL.value;

  set Dart_CloseNativePort_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Int64)>> value,
  ) => _Dart_CloseNativePort_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>>
  >
  _Dart_IsError_DL =
      _lookup<ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>>>(
        'Dart_IsError_DL',
      );

  ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>>
  get Dart_IsError_DL => _Dart_IsError_DL.value;

  set Dart_IsError_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>> value,
  ) => _Dart_IsError_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>>
  >
  _Dart_IsApiError_DL =
      _lookup<ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>>>(
        'Dart_IsApiError_DL',
      );

  ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>>
  get Dart_IsApiError_DL => _Dart_IsApiError_DL.value;

  set Dart_IsApiError_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>> value,
  ) => _Dart_IsApiError_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>>
  >
  _Dart_IsUnhandledExceptionError_DL =
      _lookup<ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>>>(
        'Dart_IsUnhandledExceptionError_DL',
      );

  ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>>
  get Dart_IsUnhandledExceptionError_DL =>
      _Dart_IsUnhandledExceptionError_DL.value;

  set Dart_IsUnhandledExceptionError_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>> value,
  ) => _Dart_IsUnhandledExceptionError_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>>
  >
  _Dart_IsCompilationError_DL =
      _lookup<ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>>>(
        'Dart_IsCompilationError_DL',
      );

  ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>>
  get Dart_IsCompilationError_DL => _Dart_IsCompilationError_DL.value;

  set Dart_IsCompilationError_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>> value,
  ) => _Dart_IsCompilationError_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>>
  >
  _Dart_IsFatalError_DL =
      _lookup<ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>>>(
        'Dart_IsFatalError_DL',
      );

  ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>>
  get Dart_IsFatalError_DL => _Dart_IsFatalError_DL.value;

  set Dart_IsFatalError_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>> value,
  ) => _Dart_IsFatalError_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Handle)>>
  >
  _Dart_GetError_DL =
      _lookup<
        ffi.Pointer<
          ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Handle)>
        >
      >('Dart_GetError_DL');

  ffi.Pointer<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Handle)>>
  get Dart_GetError_DL => _Dart_GetError_DL.value;

  set Dart_GetError_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Handle)>>
    value,
  ) => _Dart_GetError_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>>
  >
  _Dart_ErrorHasException_DL =
      _lookup<ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>>>(
        'Dart_ErrorHasException_DL',
      );

  ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>>
  get Dart_ErrorHasException_DL => _Dart_ErrorHasException_DL.value;

  set Dart_ErrorHasException_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>> value,
  ) => _Dart_ErrorHasException_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Handle)>>
  >
  _Dart_ErrorGetException_DL =
      _lookup<ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Handle)>>>(
        'Dart_ErrorGetException_DL',
      );

  ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Handle)>>
  get Dart_ErrorGetException_DL => _Dart_ErrorGetException_DL.value;

  set Dart_ErrorGetException_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Handle)>> value,
  ) => _Dart_ErrorGetException_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Handle)>>
  >
  _Dart_ErrorGetStackTrace_DL =
      _lookup<ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Handle)>>>(
        'Dart_ErrorGetStackTrace_DL',
      );

  ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Handle)>>
  get Dart_ErrorGetStackTrace_DL => _Dart_ErrorGetStackTrace_DL.value;

  set Dart_ErrorGetStackTrace_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Handle)>> value,
  ) => _Dart_ErrorGetStackTrace_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Pointer<ffi.Char>)>>
  >
  _Dart_NewApiError_DL =
      _lookup<
        ffi.Pointer<
          ffi.NativeFunction<ffi.Handle Function(ffi.Pointer<ffi.Char>)>
        >
      >('Dart_NewApiError_DL');

  ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Pointer<ffi.Char>)>>
  get Dart_NewApiError_DL => _Dart_NewApiError_DL.value;

  set Dart_NewApiError_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Pointer<ffi.Char>)>>
    value,
  ) => _Dart_NewApiError_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Pointer<ffi.Char>)>>
  >
  _Dart_NewCompilationError_DL =
      _lookup<
        ffi.Pointer<
          ffi.NativeFunction<ffi.Handle Function(ffi.Pointer<ffi.Char>)>
        >
      >('Dart_NewCompilationError_DL');

  ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Pointer<ffi.Char>)>>
  get Dart_NewCompilationError_DL => _Dart_NewCompilationError_DL.value;

  set Dart_NewCompilationError_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Pointer<ffi.Char>)>>
    value,
  ) => _Dart_NewCompilationError_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Handle)>>
  >
  _Dart_NewUnhandledExceptionError_DL =
      _lookup<ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Handle)>>>(
        'Dart_NewUnhandledExceptionError_DL',
      );

  ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Handle)>>
  get Dart_NewUnhandledExceptionError_DL =>
      _Dart_NewUnhandledExceptionError_DL.value;

  set Dart_NewUnhandledExceptionError_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Handle)>> value,
  ) => _Dart_NewUnhandledExceptionError_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Handle)>>
  >
  _Dart_PropagateError_DL =
      _lookup<ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Handle)>>>(
        'Dart_PropagateError_DL',
      );

  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Handle)>>
  get Dart_PropagateError_DL => _Dart_PropagateError_DL.value;

  set Dart_PropagateError_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Handle)>> value,
  ) => _Dart_PropagateError_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Handle)>>
  >
  _Dart_HandleFromPersistent_DL =
      _lookup<ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Handle)>>>(
        'Dart_HandleFromPersistent_DL',
      );

  ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Handle)>>
  get Dart_HandleFromPersistent_DL => _Dart_HandleFromPersistent_DL.value;

  set Dart_HandleFromPersistent_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Handle)>> value,
  ) => _Dart_HandleFromPersistent_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Handle Function(ffi.Pointer<_Dart_WeakPersistentHandle>)
      >
    >
  >
  _Dart_HandleFromWeakPersistent_DL =
      _lookup<
        ffi.Pointer<
          ffi.NativeFunction<
            ffi.Handle Function(ffi.Pointer<_Dart_WeakPersistentHandle>)
          >
        >
      >('Dart_HandleFromWeakPersistent_DL');

  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Handle Function(ffi.Pointer<_Dart_WeakPersistentHandle>)
    >
  >
  get Dart_HandleFromWeakPersistent_DL =>
      _Dart_HandleFromWeakPersistent_DL.value;

  set Dart_HandleFromWeakPersistent_DL(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Handle Function(ffi.Pointer<_Dart_WeakPersistentHandle>)
      >
    >
    value,
  ) => _Dart_HandleFromWeakPersistent_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Handle)>>
  >
  _Dart_NewPersistentHandle_DL =
      _lookup<ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Handle)>>>(
        'Dart_NewPersistentHandle_DL',
      );

  ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Handle)>>
  get Dart_NewPersistentHandle_DL => _Dart_NewPersistentHandle_DL.value;

  set Dart_NewPersistentHandle_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Handle)>> value,
  ) => _Dart_NewPersistentHandle_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Handle, ffi.Handle)>>
  >
  _Dart_SetPersistentHandle_DL =
      _lookup<
        ffi.Pointer<
          ffi.NativeFunction<ffi.Void Function(ffi.Handle, ffi.Handle)>
        >
      >('Dart_SetPersistentHandle_DL');

  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Handle, ffi.Handle)>>
  get Dart_SetPersistentHandle_DL => _Dart_SetPersistentHandle_DL.value;

  set Dart_SetPersistentHandle_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Handle, ffi.Handle)>>
    value,
  ) => _Dart_SetPersistentHandle_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Handle)>>
  >
  _Dart_DeletePersistentHandle_DL =
      _lookup<ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Handle)>>>(
        'Dart_DeletePersistentHandle_DL',
      );

  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Handle)>>
  get Dart_DeletePersistentHandle_DL => _Dart_DeletePersistentHandle_DL.value;

  set Dart_DeletePersistentHandle_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Handle)>> value,
  ) => _Dart_DeletePersistentHandle_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Pointer<_Dart_WeakPersistentHandle> Function(
          ffi.Handle,
          ffi.Pointer<ffi.Void>,
          ffi.IntPtr,
          ffi.Pointer<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >,
        )
      >
    >
  >
  _Dart_NewWeakPersistentHandle_DL =
      _lookup<
        ffi.Pointer<
          ffi.NativeFunction<
            ffi.Pointer<_Dart_WeakPersistentHandle> Function(
              ffi.Handle,
              ffi.Pointer<ffi.Void>,
              ffi.IntPtr,
              ffi.Pointer<
                ffi.NativeFunction<
                  ffi.Void Function(
                    ffi.Pointer<ffi.Void>,
                    ffi.Pointer<ffi.Void>,
                  )
                >
              >,
            )
          >
        >
      >('Dart_NewWeakPersistentHandle_DL');

  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<_Dart_WeakPersistentHandle> Function(
        ffi.Handle,
        ffi.Pointer<ffi.Void>,
        ffi.IntPtr,
        ffi.Pointer<
          ffi.NativeFunction<
            ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
          >
        >,
      )
    >
  >
  get Dart_NewWeakPersistentHandle_DL => _Dart_NewWeakPersistentHandle_DL.value;

  set Dart_NewWeakPersistentHandle_DL(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Pointer<_Dart_WeakPersistentHandle> Function(
          ffi.Handle,
          ffi.Pointer<ffi.Void>,
          ffi.IntPtr,
          ffi.Pointer<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >,
        )
      >
    >
    value,
  ) => _Dart_NewWeakPersistentHandle_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<_Dart_WeakPersistentHandle>)
      >
    >
  >
  _Dart_DeleteWeakPersistentHandle_DL =
      _lookup<
        ffi.Pointer<
          ffi.NativeFunction<
            ffi.Void Function(ffi.Pointer<_Dart_WeakPersistentHandle>)
          >
        >
      >('Dart_DeleteWeakPersistentHandle_DL');

  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<_Dart_WeakPersistentHandle>)
    >
  >
  get Dart_DeleteWeakPersistentHandle_DL =>
      _Dart_DeleteWeakPersistentHandle_DL.value;

  set Dart_DeleteWeakPersistentHandle_DL(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<_Dart_WeakPersistentHandle>)
      >
    >
    value,
  ) => _Dart_DeleteWeakPersistentHandle_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Pointer<_Dart_FinalizableHandle> Function(
          ffi.Handle,
          ffi.Pointer<ffi.Void>,
          ffi.IntPtr,
          ffi.Pointer<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >,
        )
      >
    >
  >
  _Dart_NewFinalizableHandle_DL =
      _lookup<
        ffi.Pointer<
          ffi.NativeFunction<
            ffi.Pointer<_Dart_FinalizableHandle> Function(
              ffi.Handle,
              ffi.Pointer<ffi.Void>,
              ffi.IntPtr,
              ffi.Pointer<
                ffi.NativeFunction<
                  ffi.Void Function(
                    ffi.Pointer<ffi.Void>,
                    ffi.Pointer<ffi.Void>,
                  )
                >
              >,
            )
          >
        >
      >('Dart_NewFinalizableHandle_DL');

  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<_Dart_FinalizableHandle> Function(
        ffi.Handle,
        ffi.Pointer<ffi.Void>,
        ffi.IntPtr,
        ffi.Pointer<
          ffi.NativeFunction<
            ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
          >
        >,
      )
    >
  >
  get Dart_NewFinalizableHandle_DL => _Dart_NewFinalizableHandle_DL.value;

  set Dart_NewFinalizableHandle_DL(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Pointer<_Dart_FinalizableHandle> Function(
          ffi.Handle,
          ffi.Pointer<ffi.Void>,
          ffi.IntPtr,
          ffi.Pointer<
            ffi.NativeFunction<
              ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
            >
          >,
        )
      >
    >
    value,
  ) => _Dart_NewFinalizableHandle_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<_Dart_FinalizableHandle>, ffi.Handle)
      >
    >
  >
  _Dart_DeleteFinalizableHandle_DL =
      _lookup<
        ffi.Pointer<
          ffi.NativeFunction<
            ffi.Void Function(ffi.Pointer<_Dart_FinalizableHandle>, ffi.Handle)
          >
        >
      >('Dart_DeleteFinalizableHandle_DL');

  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<_Dart_FinalizableHandle>, ffi.Handle)
    >
  >
  get Dart_DeleteFinalizableHandle_DL => _Dart_DeleteFinalizableHandle_DL.value;

  set Dart_DeleteFinalizableHandle_DL(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<_Dart_FinalizableHandle>, ffi.Handle)
      >
    >
    value,
  ) => _Dart_DeleteFinalizableHandle_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<ffi.NativeFunction<ffi.Pointer<_Dart_Isolate> Function()>>
  >
  _Dart_CurrentIsolate_DL =
      _lookup<
        ffi.Pointer<ffi.NativeFunction<ffi.Pointer<_Dart_Isolate> Function()>>
      >('Dart_CurrentIsolate_DL');

  ffi.Pointer<ffi.NativeFunction<ffi.Pointer<_Dart_Isolate> Function()>>
  get Dart_CurrentIsolate_DL => _Dart_CurrentIsolate_DL.value;

  set Dart_CurrentIsolate_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Pointer<_Dart_Isolate> Function()>>
    value,
  ) => _Dart_CurrentIsolate_DL.value = value;

  late final ffi.Pointer<ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>>
  _Dart_ExitIsolate_DL =
      _lookup<ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>>(
        'Dart_ExitIsolate_DL',
      );

  ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>
  get Dart_ExitIsolate_DL => _Dart_ExitIsolate_DL.value;

  set Dart_ExitIsolate_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> value,
  ) => _Dart_ExitIsolate_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<
      ffi.NativeFunction<ffi.Void Function(ffi.Pointer<_Dart_Isolate>)>
    >
  >
  _Dart_EnterIsolate_DL =
      _lookup<
        ffi.Pointer<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<_Dart_Isolate>)>
        >
      >('Dart_EnterIsolate_DL');

  ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<_Dart_Isolate>)>>
  get Dart_EnterIsolate_DL => _Dart_EnterIsolate_DL.value;

  set Dart_EnterIsolate_DL(
    ffi.Pointer<
      ffi.NativeFunction<ffi.Void Function(ffi.Pointer<_Dart_Isolate>)>
    >
    value,
  ) => _Dart_EnterIsolate_DL.value = value;

  late final ffi.Pointer<ffi.Pointer<ffi.NativeFunction<ffi.Int64 Function()>>>
  _Dart_GetMainPortId_DL =
      _lookup<ffi.Pointer<ffi.NativeFunction<ffi.Int64 Function()>>>(
        'Dart_GetMainPortId_DL',
      );

  ffi.Pointer<ffi.NativeFunction<ffi.Int64 Function()>>
  get Dart_GetMainPortId_DL => _Dart_GetMainPortId_DL.value;

  set Dart_GetMainPortId_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Int64 Function()>> value,
  ) => _Dart_GetMainPortId_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Int64, ffi.Handle)>>
  >
  _Dart_Post_DL =
      _lookup<
        ffi.Pointer<
          ffi.NativeFunction<ffi.Bool Function(ffi.Int64, ffi.Handle)>
        >
      >('Dart_Post_DL');

  ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Int64, ffi.Handle)>>
  get Dart_Post_DL => _Dart_Post_DL.value;

  set Dart_Post_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Int64, ffi.Handle)>>
    value,
  ) => _Dart_Post_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Int64)>>
  >
  _Dart_NewSendPort_DL =
      _lookup<ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Int64)>>>(
        'Dart_NewSendPort_DL',
      );

  ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Int64)>>
  get Dart_NewSendPort_DL => _Dart_NewSendPort_DL.value;

  set Dart_NewSendPort_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(ffi.Int64)>> value,
  ) => _Dart_NewSendPort_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(Dart_PortEx_DL)>>
  >
  _Dart_NewSendPortEx_DL =
      _lookup<
        ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(Dart_PortEx_DL)>>
      >('Dart_NewSendPortEx_DL');

  ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(Dart_PortEx_DL)>>
  get Dart_NewSendPortEx_DL => _Dart_NewSendPortEx_DL.value;

  set Dart_NewSendPortEx_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Handle Function(Dart_PortEx_DL)>> value,
  ) => _Dart_NewSendPortEx_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Handle Function(ffi.Handle, ffi.Pointer<ffi.Int64>)
      >
    >
  >
  _Dart_SendPortGetId_DL =
      _lookup<
        ffi.Pointer<
          ffi.NativeFunction<
            ffi.Handle Function(ffi.Handle, ffi.Pointer<ffi.Int64>)
          >
        >
      >('Dart_SendPortGetId_DL');

  ffi.Pointer<
    ffi.NativeFunction<ffi.Handle Function(ffi.Handle, ffi.Pointer<ffi.Int64>)>
  >
  get Dart_SendPortGetId_DL => _Dart_SendPortGetId_DL.value;

  set Dart_SendPortGetId_DL(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Handle Function(ffi.Handle, ffi.Pointer<ffi.Int64>)
      >
    >
    value,
  ) => _Dart_SendPortGetId_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Handle Function(ffi.Handle, ffi.Pointer<Dart_PortEx_DL>)
      >
    >
  >
  _Dart_SendPortGetIdEx_DL =
      _lookup<
        ffi.Pointer<
          ffi.NativeFunction<
            ffi.Handle Function(ffi.Handle, ffi.Pointer<Dart_PortEx_DL>)
          >
        >
      >('Dart_SendPortGetIdEx_DL');

  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Handle Function(ffi.Handle, ffi.Pointer<Dart_PortEx_DL>)
    >
  >
  get Dart_SendPortGetIdEx_DL => _Dart_SendPortGetIdEx_DL.value;

  set Dart_SendPortGetIdEx_DL(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Handle Function(ffi.Handle, ffi.Pointer<Dart_PortEx_DL>)
      >
    >
    value,
  ) => _Dart_SendPortGetIdEx_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Int64)>>
  >
  _Dart_GetCurrentThreadOwnsIsolate_DL =
      _lookup<ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Int64)>>>(
        'Dart_GetCurrentThreadOwnsIsolate_DL',
      );

  ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Int64)>>
  get Dart_GetCurrentThreadOwnsIsolate_DL =>
      _Dart_GetCurrentThreadOwnsIsolate_DL.value;

  set Dart_GetCurrentThreadOwnsIsolate_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Int64)>> value,
  ) => _Dart_GetCurrentThreadOwnsIsolate_DL.value = value;

  late final ffi.Pointer<ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>>
  _Dart_EnterScope_DL =
      _lookup<ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>>(
        'Dart_EnterScope_DL',
      );

  ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> get Dart_EnterScope_DL =>
      _Dart_EnterScope_DL.value;

  set Dart_EnterScope_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> value,
  ) => _Dart_EnterScope_DL.value = value;

  late final ffi.Pointer<ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>>
  _Dart_ExitScope_DL =
      _lookup<ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>>>(
        'Dart_ExitScope_DL',
      );

  ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> get Dart_ExitScope_DL =>
      _Dart_ExitScope_DL.value;

  set Dart_ExitScope_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Void Function()>> value,
  ) => _Dart_ExitScope_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>>
  >
  _Dart_IsNull_DL =
      _lookup<ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>>>(
        'Dart_IsNull_DL',
      );

  ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>>
  get Dart_IsNull_DL => _Dart_IsNull_DL.value;

  set Dart_IsNull_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Bool Function(ffi.Handle)>> value,
  ) => _Dart_IsNull_DL.value = value;

  late final ffi.Pointer<ffi.Pointer<ffi.NativeFunction<ffi.Handle Function()>>>
  _Dart_Null_DL =
      _lookup<ffi.Pointer<ffi.NativeFunction<ffi.Handle Function()>>>(
        'Dart_Null_DL',
      );

  ffi.Pointer<ffi.NativeFunction<ffi.Handle Function()>> get Dart_Null_DL =>
      _Dart_Null_DL.value;

  set Dart_Null_DL(
    ffi.Pointer<ffi.NativeFunction<ffi.Handle Function()>> value,
  ) => _Dart_Null_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<_Dart_WeakPersistentHandle>, ffi.IntPtr)
      >
    >
  >
  _Dart_UpdateExternalSize_DL =
      _lookup<
        ffi.Pointer<
          ffi.NativeFunction<
            ffi.Void Function(
              ffi.Pointer<_Dart_WeakPersistentHandle>,
              ffi.IntPtr,
            )
          >
        >
      >('Dart_UpdateExternalSize_DL');

  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<_Dart_WeakPersistentHandle>, ffi.IntPtr)
    >
  >
  get Dart_UpdateExternalSize_DL => _Dart_UpdateExternalSize_DL.value;

  set Dart_UpdateExternalSize_DL(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Pointer<_Dart_WeakPersistentHandle>, ffi.IntPtr)
      >
    >
    value,
  ) => _Dart_UpdateExternalSize_DL.value = value;

  late final ffi.Pointer<
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<_Dart_FinalizableHandle>,
          ffi.Handle,
          ffi.IntPtr,
        )
      >
    >
  >
  _Dart_UpdateFinalizableExternalSize_DL =
      _lookup<
        ffi.Pointer<
          ffi.NativeFunction<
            ffi.Void Function(
              ffi.Pointer<_Dart_FinalizableHandle>,
              ffi.Handle,
              ffi.IntPtr,
            )
          >
        >
      >('Dart_UpdateFinalizableExternalSize_DL');

  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<_Dart_FinalizableHandle>,
        ffi.Handle,
        ffi.IntPtr,
      )
    >
  >
  get Dart_UpdateFinalizableExternalSize_DL =>
      _Dart_UpdateFinalizableExternalSize_DL.value;

  set Dart_UpdateFinalizableExternalSize_DL(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<_Dart_FinalizableHandle>,
          ffi.Handle,
          ffi.IntPtr,
        )
      >
    >
    value,
  ) => _Dart_UpdateFinalizableExternalSize_DL.value = value;

  /// Register a log callback. Pass NULL to disable logging.
  /// Not thread-safe — call once at startup before any pty_create().
  void pty_set_log_callback(pty_log_fn callback) {
    return _pty_set_log_callback(callback);
  }

  late final _pty_set_log_callbackPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(pty_log_fn)>>(
        'pty_set_log_callback',
      );
  late final _pty_set_log_callback = _pty_set_log_callbackPtr
      .asFunction<void Function(pty_log_fn)>();

  /// Set a Dart port for native log forwarding.
  ///
  /// When set, every native log message is posted to this port as a
  /// Dart_CObject list: [int level, String component, String message].
  /// This allows Dart to receive native log messages via ReceivePort
  /// without needing a native callback.
  ///
  /// Pass ILLEGAL_PORT (0) to disable.
  ///
  /// @param port  Dart_Port from a ReceivePort.sendPort.nativePort.
  void pty_set_log_port(int port) {
    return _pty_set_log_port(port);
  }

  late final _pty_set_log_portPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'pty_set_log_port',
      );
  late final _pty_set_log_port = _pty_set_log_portPtr
      .asFunction<void Function(int)>();

  /// Initialize the Dart Native API for dynamic linking.
  ///
  /// MUST be called once from Dart before any other pty_* function.
  /// Passes NativeApi.initializeApiDLData from the Dart side.
  ///
  /// @param data  Pointer from NativeApi.initializeApiDLData.
  /// @return 0 on success, non-zero on failure.
  int pty_init_dart_api(ffi.Pointer<ffi.Void> data) {
    return _pty_init_dart_api(data);
  }

  late final _pty_init_dart_apiPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>(
        'pty_init_dart_api',
      );
  late final _pty_init_dart_api = _pty_init_dart_apiPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  /// Create a new PTY and spawn a child process.
  ///
  /// Allocates a master/slave pair, configures terminal attributes,
  /// spawns the child, and starts background read + wait threads that
  /// post data to the given Dart ports.
  ///
  /// On Unix (macOS): uses posix_spawn() with POSIX_SPAWN_SETSID.
  /// On Unix (Linux): uses fork() + setsid() + TIOCSCTTY + execvp().
  /// On Windows:      uses CreatePseudoConsole + CreateProcessW.
  ///
  /// @param opts        Spawn options (executable, args, env, cwd, size).
  /// Caller retains ownership; fields are copied internally.
  /// @param output_port Dart ReceivePort for stdout data (Uint8List chunks).
  /// The read thread posts Dart_CObject typed data here.
  /// @param exit_port   Dart ReceivePort for exit code (int).
  /// The wait thread posts a single integer here on exit.
  /// @return Allocated PtyHandle on success, NULL on failure.
  /// On failure, call pty_error() for a description.
  ffi.Pointer<PtyHandle> pty_create(
    ffi.Pointer<PtyOptions> opts,
    int output_port,
    int exit_port,
  ) {
    return _pty_create(opts, output_port, exit_port);
  }

  late final _pty_createPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<PtyHandle> Function(
            ffi.Pointer<PtyOptions>,
            ffi.Int64,
            ffi.Int64,
          )
        >
      >('pty_create');
  late final _pty_create = _pty_createPtr
      .asFunction<
        ffi.Pointer<PtyHandle> Function(ffi.Pointer<PtyOptions>, int, int)
      >();

  /// Write data to the PTY master (stdin of the child process).
  ///
  /// @param handle  Active PTY handle from pty_create().
  /// @param data    Buffer of bytes to write.
  /// @param len     Number of bytes in data.
  /// @return Number of bytes written on success, -1 on error.
  /// On error, call pty_error() for a description.
  int pty_write(
    ffi.Pointer<PtyHandle> handle,
    ffi.Pointer<ffi.Uint8> data,
    int len,
  ) {
    return _pty_write(handle, data, len);
  }

  late final _pty_writePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<PtyHandle>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Int,
          )
        >
      >('pty_write');
  late final _pty_write = _pty_writePtr
      .asFunction<
        int Function(ffi.Pointer<PtyHandle>, ffi.Pointer<ffi.Uint8>, int)
      >();

  /// Resize the PTY terminal dimensions.
  ///
  /// Sends TIOCSWINSZ (Unix) or ResizePseudoConsole (Windows).
  /// The child process receives SIGWINCH on Unix.
  ///
  /// @param handle  Active PTY handle.
  /// @param rows    New row count (must be > 0).
  /// @param cols    New column count (must be > 0).
  /// @return 0 on success, -1 on error.
  /// On error, call pty_error() for a description.
  int pty_resize(ffi.Pointer<PtyHandle> handle, int rows, int cols) {
    return _pty_resize(handle, rows, cols);
  }

  late final _pty_resizePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<PtyHandle>, ffi.Int, ffi.Int)
        >
      >('pty_resize');
  late final _pty_resize = _pty_resizePtr
      .asFunction<int Function(ffi.Pointer<PtyHandle>, int, int)>();

  /// Get the process ID of the child.
  ///
  /// @param handle  Active PTY handle.
  /// @return Child PID (Unix) or process ID (Windows), or -1 if invalid.
  int pty_getpid(ffi.Pointer<PtyHandle> handle) {
    return _pty_getpid(handle);
  }

  late final _pty_getpidPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<PtyHandle>)>>(
        'pty_getpid',
      );
  late final _pty_getpid = _pty_getpidPtr
      .asFunction<int Function(ffi.Pointer<PtyHandle>)>();

  /// Send a signal to the child process.
  ///
  /// On Unix:    calls kill(pid, signal). Common: SIGTERM (15), SIGKILL (9).
  /// On Windows: calls TerminateProcess if signal is SIGKILL (9),
  /// otherwise sends Ctrl+C via GenerateConsoleCtrlEvent.
  ///
  /// @param handle  Active PTY handle.
  /// @param signal  Signal number to send.
  /// @return 0 on success, -1 on error.
  /// On error, call pty_error() for a description.
  int pty_kill(ffi.Pointer<PtyHandle> handle, int signal) {
    return _pty_kill(handle, signal);
  }

  late final _pty_killPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<PtyHandle>, ffi.Int)>
      >('pty_kill');
  late final _pty_kill = _pty_killPtr
      .asFunction<int Function(ffi.Pointer<PtyHandle>, int)>();

  /// Close the PTY and release all associated resources.
  ///
  /// Closes master fd (Unix) or ClosePseudoConsole (Windows),
  /// joins the read and wait threads, and frees the handle.
  ///
  /// After this call, the handle pointer is invalid.
  /// Safe to call if the child has already exited.
  /// Safe to call with NULL (no-op).
  ///
  /// @param handle  PTY handle to close, or NULL.
  void pty_close(ffi.Pointer<PtyHandle> handle) {
    return _pty_close(handle);
  }

  late final _pty_closePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<PtyHandle>)>>(
        'pty_close',
      );
  late final _pty_close = _pty_closePtr
      .asFunction<void Function(ffi.Pointer<PtyHandle>)>();

  /// Get the last error message for the calling thread.
  ///
  /// Returns a pointer to a thread-local string describing the most
  /// recent error from any pty_* function. The string is valid until
  /// the next pty_* call on the same thread.
  ///
  /// @return Error message string, or NULL if no error has occurred.
  /// The caller must NOT free this pointer.
  ffi.Pointer<ffi.Char> pty_error() {
    return _pty_error();
  }

  late final _pty_errorPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'pty_error',
      );
  late final _pty_error = _pty_errorPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();
}

/// This enum is versioned by DART_API_DL_MAJOR_VERSION, only add at the end
/// and bump the DART_API_DL_MINOR_VERSION.
final class _Dart_CObject extends ffi.Struct {
  @ffi.UnsignedInt()
  external int type;

  external UnnamedUnion1 value;
}

/// A Dart_CObject is used for representing Dart objects as native C
/// data outside the Dart heap. These objects are totally detached from
/// the Dart heap. Only a subset of the Dart objects have a
/// representation as a Dart_CObject.
///
/// The string encoding in the 'value.as_string' is UTF-8.
///
/// All the different types from dart:typed_data are exposed as type
/// kTypedData. The specific type from dart:typed_data is in the type
/// field of the as_typed_data structure. The length in the
/// as_typed_data structure is always in bytes.
///
/// The data for kTypedData is copied on message send and ownership remains with
/// the caller. The ownership of data for kExternalTyped is passed to the VM on
/// message send and returned when the VM invokes the
/// Dart_HandleFinalizer callback; a non-NULL callback must be provided.
///
/// Note that Dart_CObject_kNativePointer is intended for internal use by
/// dart:io implementation and has no connection to dart:ffi Pointer class.
/// It represents a pointer to a native resource of a known type.
/// The receiving side will only see this pointer as an integer and will not
/// see the specified finalizer.
/// The specified finalizer will only be invoked if the message is not delivered.
enum Dart_CObject_Type {
  Dart_CObject_kNull(0),
  Dart_CObject_kBool(1),
  Dart_CObject_kInt32(2),
  Dart_CObject_kInt64(3),
  Dart_CObject_kDouble(4),
  Dart_CObject_kString(5),
  Dart_CObject_kArray(6),
  Dart_CObject_kTypedData(7),
  Dart_CObject_kExternalTypedData(8),
  Dart_CObject_kSendPort(9),
  Dart_CObject_kCapability(10),
  Dart_CObject_kNativePointer(11),
  Dart_CObject_kUnsupported(12),
  Dart_CObject_kUnmodifiableExternalTypedData(13),
  Dart_CObject_kNumberOfTypes(14);

  final int value;
  const Dart_CObject_Type(this.value);

  static Dart_CObject_Type fromValue(int value) => switch (value) {
    0 => Dart_CObject_kNull,
    1 => Dart_CObject_kBool,
    2 => Dart_CObject_kInt32,
    3 => Dart_CObject_kInt64,
    4 => Dart_CObject_kDouble,
    5 => Dart_CObject_kString,
    6 => Dart_CObject_kArray,
    7 => Dart_CObject_kTypedData,
    8 => Dart_CObject_kExternalTypedData,
    9 => Dart_CObject_kSendPort,
    10 => Dart_CObject_kCapability,
    11 => Dart_CObject_kNativePointer,
    12 => Dart_CObject_kUnsupported,
    13 => Dart_CObject_kUnmodifiableExternalTypedData,
    14 => Dart_CObject_kNumberOfTypes,
    _ => throw ArgumentError("Unknown value for Dart_CObject_Type: $value"),
  };
}

final class UnnamedUnion1 extends ffi.Union {
  @ffi.Bool()
  external bool as_bool;

  @ffi.Int32()
  external int as_int32;

  @ffi.Int64()
  external int as_int64;

  @ffi.Double()
  external double as_double;

  external ffi.Pointer<ffi.Char> as_string;

  external UnnamedStruct1 as_send_port;

  external UnnamedStruct2 as_capability;

  external UnnamedStruct3 as_array;

  external UnnamedStruct4 as_typed_data;

  external UnnamedStruct5 as_external_typed_data;

  external UnnamedStruct6 as_native_pointer;
}

final class UnnamedStruct1 extends ffi.Struct {
  @ffi.Int64()
  external int id;

  @ffi.Int64()
  external int origin_id;
}

final class UnnamedStruct2 extends ffi.Struct {
  @ffi.Int64()
  external int id;
}

final class UnnamedStruct3 extends ffi.Struct {
  @ffi.IntPtr()
  external int length;

  external ffi.Pointer<ffi.Pointer<_Dart_CObject>> values;
}

final class UnnamedStruct4 extends ffi.Struct {
  @ffi.UnsignedInt()
  external int type;

  /// in elements, not bytes
  @ffi.IntPtr()
  external int length;

  external ffi.Pointer<ffi.Uint8> values;
}

/// ==========
/// Typed Data
/// ==========
enum Dart_TypedData_Type {
  Dart_TypedData_kByteData(0),
  Dart_TypedData_kInt8(1),
  Dart_TypedData_kUint8(2),
  Dart_TypedData_kUint8Clamped(3),
  Dart_TypedData_kInt16(4),
  Dart_TypedData_kUint16(5),
  Dart_TypedData_kInt32(6),
  Dart_TypedData_kUint32(7),
  Dart_TypedData_kInt64(8),
  Dart_TypedData_kUint64(9),
  Dart_TypedData_kFloat32(10),
  Dart_TypedData_kFloat64(11),
  Dart_TypedData_kInt32x4(12),
  Dart_TypedData_kFloat32x4(13),
  Dart_TypedData_kFloat64x2(14),
  Dart_TypedData_kInvalid(15);

  final int value;
  const Dart_TypedData_Type(this.value);

  static Dart_TypedData_Type fromValue(int value) => switch (value) {
    0 => Dart_TypedData_kByteData,
    1 => Dart_TypedData_kInt8,
    2 => Dart_TypedData_kUint8,
    3 => Dart_TypedData_kUint8Clamped,
    4 => Dart_TypedData_kInt16,
    5 => Dart_TypedData_kUint16,
    6 => Dart_TypedData_kInt32,
    7 => Dart_TypedData_kUint32,
    8 => Dart_TypedData_kInt64,
    9 => Dart_TypedData_kUint64,
    10 => Dart_TypedData_kFloat32,
    11 => Dart_TypedData_kFloat64,
    12 => Dart_TypedData_kInt32x4,
    13 => Dart_TypedData_kFloat32x4,
    14 => Dart_TypedData_kFloat64x2,
    15 => Dart_TypedData_kInvalid,
    _ => throw ArgumentError("Unknown value for Dart_TypedData_Type: $value"),
  };
}

final class UnnamedStruct5 extends ffi.Struct {
  @ffi.UnsignedInt()
  external int type;

  /// in elements, not bytes
  @ffi.IntPtr()
  external int length;

  external ffi.Pointer<ffi.Uint8> data;

  external ffi.Pointer<ffi.Void> peer;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
    >
  >
  callback;
}

final class UnnamedStruct6 extends ffi.Struct {
  @ffi.IntPtr()
  external int ptr;

  @ffi.IntPtr()
  external int size;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)
    >
  >
  callback;
}

final class _Dart_WeakPersistentHandle extends ffi.Opaque {}

final class _Dart_FinalizableHandle extends ffi.Opaque {}

final class _Dart_Isolate extends ffi.Opaque {}

final class Dart_PortEx_DL extends ffi.Struct {
  @ffi.Int64()
  external int port_id;

  @ffi.Int64()
  external int origin_id;
}

/// Log severity levels.
enum PtyLogLevel {
  PTY_LOG_DEBUG(0),

  /// Verbose diagnostic output.
  PTY_LOG_INFO(1),

  /// Normal lifecycle events (spawn, resize, exit).
  PTY_LOG_WARN(2),

  /// Recoverable issues (EINTR retries, EIO as EOF).
  PTY_LOG_ERROR(3);

  final int value;
  const PtyLogLevel(this.value);

  static PtyLogLevel fromValue(int value) => switch (value) {
    0 => PTY_LOG_DEBUG,
    1 => PTY_LOG_INFO,
    2 => PTY_LOG_WARN,
    3 => PTY_LOG_ERROR,
    _ => throw ArgumentError("Unknown value for PtyLogLevel: $value"),
  };
}

/// Log callback signature.
///
/// @param level     Severity (one of PtyLogLevel).
/// @param component Short tag identifying the subsystem (e.g. "spawn", "read").
/// @param message   Human-readable log message. Caller owns the string.
typedef pty_log_fn = ffi.Pointer<ffi.NativeFunction<pty_log_fnFunction>>;
typedef pty_log_fnFunction =
    ffi.Void Function(
      ffi.Int level,
      ffi.Pointer<ffi.Char> component,
      ffi.Pointer<ffi.Char> message,
    );
typedef Dartpty_log_fnFunction =
    void Function(
      int level,
      ffi.Pointer<ffi.Char> component,
      ffi.Pointer<ffi.Char> message,
    );

/// Options passed to pty_create() to configure the child process
/// and initial terminal dimensions.
final class PtyOptions extends ffi.Struct {
  /// Path to the executable to spawn (e.g. "/bin/bash").
  external ffi.Pointer<ffi.Char> executable;

  /// NULL-terminated array of argument strings.
  /// argv[0] is typically the program name.
  /// May be NULL if no arguments are needed.
  external ffi.Pointer<ffi.Pointer<ffi.Char>> arguments;

  /// NULL-terminated array of "KEY=VALUE" environment strings.
  /// May be NULL to inherit the parent environment.
  external ffi.Pointer<ffi.Pointer<ffi.Char>> environment;

  /// Working directory for the child process.
  /// May be NULL to inherit the parent's cwd.
  external ffi.Pointer<ffi.Char> working_directory;

  /// Initial number of terminal rows (height). Must be > 0.
  @ffi.Uint16()
  external int rows;

  /// Initial number of terminal columns (width). Must be > 0.
  @ffi.Uint16()
  external int cols;
}

/// Terminal size descriptor, used by pty_resize().
/// pixel_width/pixel_height are optional hints (set to 0 if unknown).
final class PtySize extends ffi.Struct {
  /// Number of character rows.
  @ffi.Uint16()
  external int rows;

  /// Number of character columns.
  @ffi.Uint16()
  external int cols;

  /// Pixel width of the terminal area (0 if unknown).
  @ffi.Uint16()
  external int pixel_width;

  /// Pixel height of the terminal area (0 if unknown).
  @ffi.Uint16()
  external int pixel_height;
}

final class PtyHandle extends ffi.Opaque {}

const int DART_PTY_WIN = 0;

const int DART_PTY_UNIX = 1;
